
# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
script = "script"
solc = "0.8.26"
src = "src"
test = "test"
libs = ["dependencies"]
fs_permissions = [{ access = "read-write", path = "./logs" }]

[dependencies]
forge-std = "1.9.3"
